### ISSUE TITLE
I have some questions about the Lco loss function I would like to ask?

### ISSUE THREAD

**Issue by Yueziyu** [yec22/Gaussian-DK#2]
May I ask why a tensor of all zeros is input to the tonemapper subnetwork when calculating the Lc0 loss?

**Comment by yec22** [comment]
Please refer to HDR-NeRF (https://xhuangcv.github.io/hdr-nerf/) for this Lc0 loss.
We directly inherit this loss from HDR-NeRF.
Yet, we find that the impact of this loss is not significant. Also, this loss is not one of our contributions either.
